>>> 'Pkg.add("CauseMap")' log
INFO: Cloning cache of CauseMap from git://github.com/cyrusmaher/CauseMap.jl.git
INFO: Installing CauseMap v0.0.3
INFO: Installing Conda v0.2.0
INFO: Installing PyCall v1.2.0
INFO: Building PyCall
INFO: No system-wide Python was found; got the following error:
could not spawn `'' -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: no such file or directory (ENOENT)
using the Python distribution in the Conda package
Fetching package metadata: ....
Solving package specifications: .........

# All requested packages already installed.
# packages in environment at /home/vagrant/.julia/v0.3/Conda/deps/usr:
#
numpy                     1.11.0                   py27_1  
INFO: PyCall is using /home/vagrant/.julia/v0.3/Conda/deps/usr/bin/python (Python 2.7.11) at /home/vagrant/.julia/v0.3/Conda/deps/usr/bin/python, libpython = /home/vagrant/.julia/v0.3/Conda/deps/usr/lib/libpython2.7.so
INFO: Package database updated
INFO: METADATA is out-of-date â€” you may not have the latest version of CauseMap
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("CauseMap")' log
Julia Version 0.3.12
Commit 80aa779 (2015-10-26 12:41 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
INFO: Testing CauseMap
Starting bootstrap test
ERROR: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named matplotlib.pyplot',)

 in pyerr_check at /home/vagrant/.julia/v0.3/PyCall/src/exception.jl:61
 in pyimport at /home/vagrant/.julia/v0.3/PyCall/src/PyCall.jl:81
 in makesingleplot at /home/vagrant/.julia/v0.3/CauseMap/src/plotting.jl:341
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /home/vagrant/.julia/v0.3/CauseMap/test/testplotting.jl, in expression starting on line 15
while loading /home/vagrant/.julia/v0.3/CauseMap/test/runtests.jl, in expression starting on line 1
==============================[ ERROR: CauseMap ]===============================

failed process: Process(`/home/vagrant/julia/bin/julia /home/vagrant/.julia/v0.3/CauseMap/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: No packages to install, update or remove
ERROR: CauseMap had test errors
 in error at error.jl:21
 in test at pkg/entry.jl:718
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in cd at pkg/dir.jl:28
 in test at pkg.jl:67
 in process_options at ./client.jl:213
 in _start at ./client.jl:354

>>> End of log
