>>> 'Pkg.add("DriftDiffusionPoissonSystems")' log
INFO: Cloning cache of DriftDiffusionPoissonSystems from git://github.com/Stivanification/DriftDiffusionPoissonSystems.jl.git
INFO: Cloning cache of EllipticFEM from git://github.com/gerhardtulzer/EllipticFEM.jl.git
INFO: Installing BinDeps v0.4.7
INFO: Installing ColorTypes v0.2.12
INFO: Installing Colors v0.6.9
INFO: Installing Conda v0.6.2
INFO: Installing DriftDiffusionPoissonSystems v0.0.1
INFO: Installing EllipticFEM v0.0.1
INFO: Installing FixedPointNumbers v0.2.1
INFO: Installing LaTeXStrings v0.2.1
INFO: Installing MacroTools v0.3.7
INFO: Installing PyCall v1.11.1
INFO: Installing PyPlot v2.3.2
INFO: Installing Reexport v0.0.3
INFO: Installing SHA v0.3.3
INFO: Installing URIParser v0.1.8
INFO: Building Conda
INFO: Building PyCall
INFO: Using the Python distribution in the Conda package by default.
To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").
Fetching package metadata ...............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/vagrant/.julia/v0.4/Conda/deps/usr:
#
numpy                     1.13.3          py27_blas_openblas_201  [blas_openblas]  conda-forge
INFO: PyCall is using /home/vagrant/.julia/v0.4/Conda/deps/usr/bin/python (Python 2.7.14) at /home/vagrant/.julia/v0.4/Conda/deps/usr/bin/python, libpython = /home/vagrant/.julia/v0.4/Conda/deps/usr/lib/libpython2.7
INFO: /home/vagrant/.julia/v0.4/PyCall/deps/deps.jl has not changed
INFO: /home/vagrant/.julia/v0.4/PyCall/deps/PYTHON has not changed
INFO: Package database updated
INFO: METADATA is out-of-date â€” you may not have the latest version of DriftDiffusionPoissonSystems
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("DriftDiffusionPoissonSystems")' log
Julia Version 0.4.7
Commit ae26b25 (2016-09-18 16:17 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-135-generic #184-Ubuntu SMP Wed Oct 18 11:55:51 UTC 2017 x86_64 x86_64
Memory: 2.93927001953125 GB (632.59765625 MB free)
Uptime: 30753.0 sec
Load Avg:  0.9921875  1.01611328125  1.04541015625
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3499 MHz    1426216 s       6478 s     100826 s    1260529 s         47 s
#2  3499 MHz    1015592 s         73 s      86259 s    1855869 s          0 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-8-openjdk-amd64
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.4
2 required packages:
 - DriftDiffusionPoissonSystems  0.0.1
 - JSON                          0.9.1
14 additional packages:
 - BinDeps                       0.4.7
 - ColorTypes                    0.2.12
 - Colors                        0.6.9
 - Compat                        0.26.0
 - Conda                         0.6.2
 - EllipticFEM                   0.0.1
 - FixedPointNumbers             0.2.1
 - LaTeXStrings                  0.2.1
 - MacroTools                    0.3.7
 - PyCall                        1.11.1
 - PyPlot                        2.3.2
 - Reexport                      0.0.3
 - SHA                           0.3.3
 - URIParser                     0.1.8
INFO: Testing DriftDiffusionPoissonSystems
WARNING: No working GUI backend found for matplotlib
ERROR: LoadError: LoadError: LoadError: InitError: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError("/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/../../.././libpng16.so.16)",)
  File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/contour.py", line 21, in <module>
    import matplotlib.font_manager as font_manager
  File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/font_manager.py", line 58, in <module>
    from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir

 [inlined code] from /home/vagrant/.julia/v0.4/PyCall/src/exception.jl:81
 in pyimport at /home/vagrant/.julia/v0.4/PyCall/src/PyCall.jl:392
 in __init__ at /home/vagrant/.julia/v0.4/PyPlot/src/init.jl:184
 in _include_from_serialized at loading.jl:62
 in _require_from_serialized at loading.jl:87
 in require at ./loading.jl:256
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:333
 in require at ./loading.jl:273
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:333
 in require at ./loading.jl:273
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:333
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
during initialization of module PyPlot
while loading /home/vagrant/.julia/v0.4/EllipticFEM/src/EllipticFEM.jl, in expression starting on line 3
while loading /home/vagrant/.julia/v0.4/DriftDiffusionPoissonSystems/src/DriftDiffusionPoissonSystems.jl, in expression starting on line 3
while loading /home/vagrant/.julia/v0.4/DriftDiffusionPoissonSystems/test/runtests.jl, in expression starting on line 1
====================[ ERROR: DriftDiffusionPoissonSystems ]=====================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/DriftDiffusionPoissonSystems/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: DriftDiffusionPoissonSystems had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
 in process_options at ./client.jl:257
 in _start at ./client.jl:378

>>> End of log
