>>> 'Pkg.add("GeographicLibPy")' log
INFO: Cloning cache of GeographicLibPy from https://github.com/kshramt/GeographicLibPy.jl.git
INFO: Installing Conda v1.0.0
INFO: Installing GeographicLibPy v0.0.3
INFO: Installing MacroTools v0.4.2
INFO: Installing PyCall v1.17.1
INFO: Installing VersionParsing v1.1.1
INFO: Building Conda
INFO: Building PyCall
Info: Using the Python distribution in the Conda package by default.
To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").
Info: Running `conda install -y numpy` in root environment
Solving environment: ...working... done

# All requested packages already installed.

Info: PyCall is using /home/vagrant/.julia/v0.6/Conda/deps/usr/bin/python (Python 3.7.0) at /home/vagrant/.julia/v0.6/Conda/deps/usr/bin/python, libpython = /home/vagrant/.julia/v0.6/Conda/deps/usr/lib/libpython3.7m
Info: /home/vagrant/.julia/v0.6/PyCall/deps/deps.jl has not changed
Info: /home/vagrant/.julia/v0.6/PyCall/deps/PYTHON has not changed
INFO: Package database updated
INFO: METADATA is out-of-date â€” you may not have the latest version of GeographicLibPy
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("GeographicLibPy")' log
Julia Version 0.6.4
Commit 9d11f62bcb (2018-07-09 19:09 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64
Memory: 2.939197540283203 GB (849.71484375 MB free)
Uptime: 5273.0 sec
Load Avg:  0.9453125  1.00634765625  0.98046875
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3499 MHz     288072 s         31 s      34164 s     138004 s          4 s
#2  3499 MHz      84425 s        147 s      20296 s     410915 s          0 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem MAX_THREADS=16)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-8-openjdk-amd64
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.6
2 required packages:
 - GeographicLibPy               0.0.3
 - JSON                          0.17.2
6 additional packages:
 - Compat                        1.0.0
 - Conda                         1.0.0
 - MacroTools                    0.4.2
 - Nullables                     0.0.6
 - PyCall                        1.17.1
 - VersionParsing                1.1.1
INFO: Testing GeographicLibPy
ERROR: LoadError: InitError: PyError (PyImport_ImportModule) <class 'ModuleNotFoundError'>
ModuleNotFoundError("No module named 'geographiclib'")

Stacktrace:
 [1] pyimport(::String) at /home/vagrant/.julia/v0.6/PyCall/src/PyCall.jl:473
 [2] __init__() at /home/vagrant/.julia/v0.6/GeographicLibPy/src/GeographicLibPy.jl:16
 [3] _include_from_serialized(::String) at ./loading.jl:157
 [4] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [5] _require(::Symbol) at ./loading.jl:498
 [6] require(::Symbol) at ./loading.jl:405
 [7] include_from_node1(::String) at ./loading.jl:576
 [8] include(::String) at ./sysimg.jl:14
 [9] process_options(::Base.JLOptions) at ./client.jl:305
 [10] _start() at ./client.jl:371
during initialization of module GeographicLibPy
while loading /home/vagrant/.julia/v0.6/GeographicLibPy/test/runtests.jl, in expression starting on line 3
===========================[ ERROR: GeographicLibPy ]===========================

failed process: Process(`/home/vagrant/julia/bin/julia -Cgeneric -J/home/vagrant/julia/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=no --compilecache=yes /home/vagrant/.julia/v0.6/GeographicLibPy/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: GeographicLibPy had test errors

>>> End of log
