INFO: Installing PyCall v0.4.6
INFO: Package database updated
ERROR: test failed: collect(PyObject([1,3,5])) == [1,3,5]
 in error at error.jl:21
 in default_handler at test.jl:19
 in do_test at test.jl:39
 in include at ./boot.jl:244
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /home/idunning/pkgtest/.julia/v0.3/PyCall/test/runtests.jl, in expression starting on line 66
INFO: Package database updated
